"""RADAR — Radiation Analysis and Design Assessment Resource."""

from radar.version import __version__
from radar.calculation_protocol import (
    CalculationProtocolEntry,
    calculation_protocol_entries,
    calculation_protocol_snapshot,
    calculation_protocol_text,
    methodology_profile_title,
    source_model_family_title,
)
from radar.core.project import (
    CalculationConfig,
    MethodologyConfig,
    MissionConfig,
    OrbitConfig,
    ShieldingConfig,
    SourceModelSelectionConfig,
)
from radar.core.project_snapshot import (
    source_model_selection_from_snapshot,
    shielding_config_from_snapshot,
    orbit_config_from_snapshot,
    mission_config_from_snapshot,
    methodology_config_from_snapshot,
    calculation_config_from_snapshot_json,
    calculation_config_from_snapshot,
    calculation_config_snapshot,
    calculation_config_snapshot_json,
    methodology_config_snapshot,
    mission_config_snapshot,
    orbit_config_snapshot,
    shielding_config_snapshot,
    source_model_selection_snapshot,
)
from radar.core.result import CalculationResult
from radar.core.spectra import Spectrum1D
from radar.project_io import (
    load_project_config,
    read_project_file,
    save_project_file,
)
from radar.project_metadata import PROJECT_PROGRAM_NAME, PROJECT_SCHEMA_VERSION
from radar.project_file import (
    ProjectFile,
    project_file_from_dict,
    project_file_from_json,
)
from radar.model_registry import (
    REGISTERED_SOURCE_MODELS,
    SourceModelBundle,
    SourceModelRegistration,
    registered_source_model_families,
    source_model_bundle_for_profile,
    source_model_bundle_for_selection,
    source_model_class,
    source_model_class_for_profile,
    source_model_classes_for_profile,
    source_model_classes_for_selection,
    source_model_registration,
    source_model_registration_for_profile,
)


__all__ = [
    "CalculationConfig",
    "source_model_family_title",
    "methodology_profile_title",
    "calculation_protocol_text",
    "calculation_protocol_snapshot",
    "calculation_protocol_entries",
    "CalculationProtocolEntry",
    "CalculationResult",
    "MethodologyConfig",
    "MissionConfig",
    "OrbitConfig",
    "project_file_from_json",
    "save_project_file",
    "read_project_file",
    "load_project_config",
    "project_file_from_dict",
    "ProjectFile",
    "PROJECT_SCHEMA_VERSION",
    "PROJECT_PROGRAM_NAME",
    "REGISTERED_SOURCE_MODELS",
    "ShieldingConfig",
    "SourceModelBundle",
    "SourceModelRegistration",
    "SourceModelSelectionConfig",
    "Spectrum1D",
    "__version__",
    "source_model_selection_snapshot",
    "shielding_config_snapshot",
    "orbit_config_snapshot",
    "mission_config_snapshot",
    "methodology_config_snapshot",
    "calculation_config_snapshot_json",
    "calculation_config_snapshot",
    "source_model_selection_from_snapshot",
    "shielding_config_from_snapshot",
    "orbit_config_from_snapshot",
    "mission_config_from_snapshot",
    "methodology_config_from_snapshot",
    "calculation_config_from_snapshot_json",
    "calculation_config_from_snapshot",
    "registered_source_model_families",
    "source_model_bundle_for_profile",
    "source_model_bundle_for_selection",
    "source_model_class",
    "source_model_class_for_profile",
    "source_model_classes_for_profile",
    "source_model_classes_for_selection",
    "source_model_registration",
    "source_model_registration_for_profile",
]
