"""RADAR calculation core."""

from radar.core.dose_units import (
    default_dose_unit_for_radiation_quantity_mode,
    dose_quantity_for_radiation_quantity_mode,
    dose_quantity_for_spectrum_quantity,
    is_accumulated_dose_unit,
    is_dose_rate_unit,
    radiation_quantity_mode_for_spectrum_quantity,
    validate_dose_quantity_for_radiation_quantity_mode,
    validate_dose_settings_for_radiation_quantity_mode,
    validate_dose_unit_for_quantity,
)
from radar.core.log import CalculationLog, CalculationLogEntry, LogLevel
from radar.core.product_display import (
    average_daily_spectrum_for_mission_years,
    average_daily_spectrum_for_product,
    daily_display_unit_for_product_kind,
)
from radar.core.products import (
    SpectrumProduct,
    allowed_spectrum_quantities_for_product_kind,
    default_dose_unit_for_product_kind,
    dose_quantity_for_product_kind,
    radiation_quantity_mode_for_product_kind,
    expected_spectrum_unit_for_product_kind,
    validate_spectrum_matches_product_kind,
)
from radar.core.profiles import (
    DEFAULT_METHODOLOGY_PROFILE,
    GOST_GCR_DOCUMENT,
    GOST_SEP_DOCUMENT,
    METHODOLOGY_PROFILE_SPECS,
    METHODOLOGY_SOURCE_MODEL_CONTRACTS,
    OST_134_1044_2007_DOCUMENT,
    MethodologyProfile,
    MethodologyProfileSpec,
    MethodologySourceModelContract,
    SourceModelFamily,
    documents_for_methodology_profile,
    expected_source_model_family_for_profile,
    methodology_profile_spec,
    profile_uses_gost_gcr,
    profile_uses_gost_sep,
    profile_uses_ost_134_1044_2007,
    source_model_contract_for_profile,
    validate_source_model_family_for_profile,
)
from radar.core.project import (
    CalculationConfig,
    MethodologyConfig,
    MissionConfig,
    OrbitConfig,
    ShieldingConfig,
    SourceModelSelectionConfig,
)
from radar.core.result import CalculationResult, ComponentStatus, ModelInfo
from radar.core.spectra import Spectrum1D
from radar.core.source_products import (
    allowed_product_kinds_for_source,
    is_product_kind_allowed_for_source,
    validate_product_allowed_for_source,
    validate_product_spectra_match_spectra,
    validate_products_allowed_for_source,
    validate_products_match_spectra_and_source,
    validate_product_kind_allowed_for_source,
    validate_spectra_match_expected,
)
from radar.core.spectrum_ops import add_spectra, check_spectra_compatible, scale_spectrum
from radar.core.types import DoseQuantity, RadiationProductKind, RadiationQuantityMode

__all__ = [
    "CalculationConfig",
    "CalculationLog",
    "CalculationLogEntry",
    "CalculationResult",
    "ComponentStatus",
    "DoseQuantity",
    "LogLevel",
    "MissionConfig",
    "SourceModelSelectionConfig",
    "MethodologyConfig",
    "profile_uses_ost_134_1044_2007",
    "profile_uses_gost_sep",
    "profile_uses_gost_gcr",
    "methodology_profile_spec",
    "documents_for_methodology_profile",
    "OST_134_1044_2007_DOCUMENT",
    "MethodologyProfileSpec",
    "validate_source_model_family_for_profile",
    "source_model_contract_for_profile",
    "expected_source_model_family_for_profile",
    "SourceModelFamily",
    "MethodologySourceModelContract",
    "METHODOLOGY_SOURCE_MODEL_CONTRACTS",
    "MethodologyProfile",
    "METHODOLOGY_PROFILE_SPECS",
    "GOST_SEP_DOCUMENT",
    "GOST_GCR_DOCUMENT",
    "DEFAULT_METHODOLOGY_PROFILE",
    "ModelInfo",
    "OrbitConfig",
    "RadiationProductKind",
    "RadiationQuantityMode",
    "ShieldingConfig",
    "Spectrum1D",
    "SpectrumProduct",
    "average_daily_spectrum_for_mission_years",
    "average_daily_spectrum_for_product",
    "add_spectra",
    "allowed_product_kinds_for_source",
    "allowed_spectrum_quantities_for_product_kind",
    "check_spectra_compatible",
    "daily_display_unit_for_product_kind",
    "default_dose_unit_for_product_kind",
    "expected_spectrum_unit_for_product_kind",
    "default_dose_unit_for_radiation_quantity_mode",
    "dose_quantity_for_product_kind",
    "dose_quantity_for_radiation_quantity_mode",
    "dose_quantity_for_spectrum_quantity",
    "is_accumulated_dose_unit",
    "is_dose_rate_unit",
    "is_product_kind_allowed_for_source",
    "radiation_quantity_mode_for_product_kind",
    "radiation_quantity_mode_for_spectrum_quantity",
    "scale_spectrum",
    "validate_dose_quantity_for_radiation_quantity_mode",
    "validate_dose_settings_for_radiation_quantity_mode",
    "validate_dose_unit_for_quantity",
    "validate_product_allowed_for_source",
    "validate_product_spectra_match_spectra",
    "validate_products_allowed_for_source",
    "validate_products_match_spectra_and_source",
    "validate_product_kind_allowed_for_source",
    "validate_spectra_match_expected",
    "validate_spectrum_matches_product_kind",
]
